### ISSUE TITLE
SC on OLE

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#137]
```python
OLE: stdout
Traceback (most recent call last):
  File "C:\Users\Tudor\Desktop\judge\judge.py", line 561, in run
    process.kill()
  File "C:\Users\Tudor\Desktop\judge\wbox\sandbox.py", line 77, in kill
    self.process.terminate(code)
  File "wbox\_wbox.pyx", line 212, in wbox._wbox.ProcessManager.terminate (_wbox.cpp:3181)
    return self.thisptr.terminate(code)
RuntimeError: TerminateProcess: 5
```

**Comment by Xyene** [comment]
This still occurs with the latest wbox.

**Comment by quantum5** [comment]
`TLE` on `OLE` is caused by `safe_communicate` blocking on both streams. Breaking from one stream due to OLE will not cause the `join` on the other to terminate.

Suggested solution:

* `OpenThread()` on `thread.ident` which is tid.
* `WaitForMultipleObjects()` with `FALSE` for `bWaitAll`.

**Comment by Xyene** [comment]
This is fixed.
