### ISSUE TITLE
AMQP client ping does not check for connection

### ISSUE THREAD

**Issue by quantum5** [DMOJ/judge#145]
```pytb
ERROR 2016-03-05 15:54:41,579 packet Exception in pika loop
Traceback (most recent call last):
  File "/home/judge/judge/packet.py", line 485, in run
    self.conn.ioloop.start()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 355, in start
    self.process_timeouts()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 283, in process_timeouts
    timer['callback']()
  File "/home/judge/judge/packet.py", line 410, in ping_packet
    self._send_ping_packet(packet)
  File "/home/judge/judge/packet.py", line 386, in _send_ping_packet
    self.submission_chan.basic_publish(exchange='', routing_key='judge-ping', body=json.dumps(packet).encode('zlib'))
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by Xyene** [comment]
AMQP is no longer used.
