### ISSUE TITLE
Java Date API broken on Windows

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#153]
```
java.util.MissingResourceException: Can't find bundle for base name sun.util.res
ources.CalendarData, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle
.java:1499)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:841)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:142)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:140)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.util.resources.LocaleData.getBundle(LocaleData.java:140)
        at sun.util.resources.LocaleData.getCalendarData(LocaleData.java:88)
        at java.util.Calendar.setWeekCountData(Calendar.java:2590)
        at java.util.Calendar.<init>(Calendar.java:956)
        at java.util.GregorianCalendar.<init>(GregorianCalendar.java:619)
        at java.util.Calendar.createCalendar(Calendar.java:1030)
        at java.util.Calendar.getInstance(Calendar.java:1013)
        at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:6
82)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:581)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:560)
        at Main.main(Main.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at ca.dmoj.java.SubmissionThread.run(SubmissionThread.java:27)
Caused by: java.security.AccessControlException: class java.io.FilePermission -
C:\Program Files\Java\jdk1.7.0_79\jre\lib\rt.jar: read
        at ca.dmoj.java.SubmissionSecurityManager.checkPermission(SubmissionSecu
rityManager.java:89)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.isDirectory(File.java:838)
        at sun.net.www.ParseUtil.fileToEncodedURL(ParseUtil.java:269)
        at java.lang.Package$1.run(Package.java:550)
        at java.lang.Package$1.run(Package.java:541)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.Package.defineSystemPackage(Package.java:541)
        at java.lang.Package.getSystemPackage(Package.java:517)
        at java.lang.Package.getPackage(Package.java:334)
        at java.lang.Class.getPackage(Class.java:722)
        at ca.dmoj.java.SubmissionSecurityManager.checkPermission(SubmissionSecu
rityManager.java:26)
        at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.jav
a:128)
        at java.lang.Class$1.run(Class.java:358)
        at java.lang.Class$1.run(Class.java:356)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.Class.newInstance(Class.java:355)
        at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2572)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1436)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1400)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1296)
        ... 20 more
java.util.MissingResourceException: Can't find bundle for base name sun.util.res
ources.CalendarData, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle
.java:1499)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:841)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:142)
        at sun.util.resources.LocaleData$1.run(LocaleData.java:140)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.util.resources.LocaleData.getBundle(LocaleData.java:140)
        at sun.util.resources.LocaleData.getCalendarData(LocaleData.java:88)
        at java.util.Calendar.setWeekCountData(Calendar.java:2590)
        at java.util.Calendar.<init>(Calendar.java:956)
        at java.util.GregorianCalendar.<init>(GregorianCalendar.java:619)
        at java.util.Calendar.createCalendar(Calendar.java:1030)
        at java.util.Calendar.getInstance(Calendar.java:1013)
        at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:6
82)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:581)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:560)
        at Main.main(Main.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at ca.dmoj.java.SubmissionThread.run(SubmissionThread.java:27)
Caused by: java.security.AccessControlException: class java.io.FilePermission -
C:\Program Files\Java\jdk1.7.0_79\jre\lib\rt.jar: read
        at ca.dmoj.java.SubmissionSecurityManager.checkPermission(SubmissionSecu
rityManager.java:89)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.isDirectory(File.java:838)
        at sun.net.www.ParseUtil.fileToEncodedURL(ParseUtil.java:269)
        at java.lang.Package$1.run(Package.java:550)
        at java.lang.Package$1.run(Package.java:541)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.Package.defineSystemPackage(Package.java:541)
        at java.lang.Package.getSystemPackage(Package.java:517)
        at java.lang.Package.getPackage(Package.java:334)
        at java.lang.Class.getPackage(Class.java:722)
        at ca.dmoj.java.SubmissionSecurityManager.checkPermission(SubmissionSecu
rityManager.java:26)
        at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.jav
a:128)
        at java.lang.Class$1.run(Class.java:358)
        at java.lang.Class$1.run(Class.java:356)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.lang.Class.newInstance(Class.java:355)
        at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2572)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1436)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1400)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1296)
        ... 20 more
```

**Comment by Xyene** [comment]
Fixed.
