### ISSUE TITLE
Windows Linux subsystem judge

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#159]
Windows 10 has a Linux subsystem, and the judge runs on it, almost.

`os.getloadavg`, used in `sysinfo`, raises `OSError` due to it being unimplemented.

Oftentimes the grader hangs (making self-tests a game of RNG):

``` python
Traceback (most recent call last):
  File "/home/quantum/judge/freeze_main.py", line 52, in <module>
  File "/mnt/c/Users/Smaranda/test/judge.py", line 46, in <module>
    from executors import executors
  File "/mnt/c/Users/Smaranda/test/executors/__init__.py", line 49, in <module>
    __load(__executors)
  File "/mnt/c/Users/Smaranda/test/executors/__init__.py", line 40, in __load
    if hasattr(executor, 'initialize') and not executor.initialize(sandbox=env.get('selftest_sandboxing', True)):
  File "/mnt/c/Users/Smaranda/test/executors/GCCExecutor.py", line 86, in initialize
    return super(CompiledExecutor, cls).initialize(sandbox=sandbox)
  File "/mnt/c/Users/Smaranda/test/executors/base_executor.py", line 126, in initialize
    return cls.run_self_test(sandbox)
  File "/mnt/c/Users/Smaranda/test/executors/base_executor.py", line 139, in run_self_test
    stdout, stderr = proc.communicate(test_message + '\n')
  File "/mnt/c/Users/Smaranda/test/cptbox/sandbox.py", line 272, in communicate
    return self._communicate(input)
  File "/mnt/c/Users/Smaranda/test/cptbox/sandbox.py", line 312, in _communicate
    ready = poller.poll()
KeyboardInterrupt
```

`/proc/self/status` also appears to be largely unimplemented, with the `Vm*` fields all zeroed.

Would still be very cool if this worked.

@WallE256 @quantum5

**Comment by Xyene** [comment]
As of build 14367, the poll syscall is fixed and `os.getloadavg` is implemented. `Vm*` fields remain unimplemented, but the judge is a lot closer to running now that it doesn't randomly hang.

**Comment by quantum5** [comment]
Judge appears to work on Windows Subsystem for Linux.
