### ISSUE TITLE
Firewall rule fails to add

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#166]
```
Self-testing PY2:    Failed
Traceback (most recent call last):
 File "c:\judge\dmoj\executors\base_executor.py", line 136, in run_self_test
   proc = executor.launch(time=cls.test_time, memory=cls.test_memory) if sandbox else executor.launch_unsafe()
 File "c:\judge\dmoj\executors\base_executor.py", line 101, in launch
   inject_func=self.get_inject_func())
 File "c:\judge\dmoj\wbox\sandbox.py", line 51, in __init__
   self.network_block = NetworkManager('wbox_%s' % uuid1(), executable)
 File "wbox\_wbox.pyx", line 137, in wbox._wbox.NetworkManager.__cinit__ (_wbox.cpp:1860)
RuntimeError: INetFwRules->Add: 0x80070057
```

Forcing `network_block` to `False` in the sandbox constructor allowed the judge to start, and function normally.

**Comment by Xyene** [comment]
Seems like this is caused by using `/` instead of `\\` when specifying runtime path &mdash; the rest of the sandbox works fine, but `INetFwRules` expects `/`.

**Comment by quantum5** [comment]
You mean `INetFwRules` expects `\\`? Also:

```
$ err 0x80070057
# for hex 0x80070057 / decimal -2147024809 :
  COR_E_ARGUMENT                                                corerror.h
# MessageText:
# An argument does not meet the contract of the method.
  DDERR_INVALIDPARAMS                                           ddraw.h
  DIERR_INVALIDPARAM                                            dinput.h
  DPERR_INVALIDPARAM                                            dplay.h
  DPERR_INVALIDPARAMS                                           dplay.h
  DPNERR_INVALIDPARAM                                           dplay8.h
  DSERR_INVALIDPARAM                                            dsound.h
  DVERR_INVALIDPARAM                                            dvoice.h
  ecInvalidParam                                                ec.h
  ecInvalidSession                                              ec.h
  ecBadBuffer                                                   ec.h
  MAPI_E_INVALID_PARAMETER                                      mapicode.h
  STIERR_INVALID_PARAM                                          stierr.h
  E_INVALIDARG                                                  winerror.h
# One or more arguments are invalid
# 14 matches found for "0x80070057"
```
