### ISSUE TITLE
None syscall callname on protection fault

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#181]
Got this error in the mail a couple days ago.

```python
Traceback (most recent call last):
  File "/code/judge/dmoj/judge.py", line 154, in _begin_grading
    short_circuit=short_circuit)):
  File "/code/judge/dmoj/judge.py", line 227, in grade_cases
    result = grader.grade(case)
  File "/code/judge/dmoj/graders/standard.py", line 46, in grade
    self.update_feedback(check, error, process, result)
  File "/code/judge/dmoj/graders/standard.py", line 60, in update_feedback
    callname = callname.replace('sys_', '', 1)
AttributeError: 'NoneType' object has no attribute 'replace'
```

<https://dmoj.ca/submission/250534>

I've been unable to reproduce the error, despite rejudging on all judges.

**Comment by Xyene** [comment]
Digging through logs the error appears to be from

```
Protection fault on: 4294967295 (None)
Arg0: 0x00000000ffffffff
Arg1: 0x00000000ffffffff
Arg2: 0x00000000ffffffff
Arg3: 0x00000000ffffffff
Arg4: 0x00000000ffffffff
Arg5: 0x0000000000000000
```

Which is rather wrong as when signed, 4294967295 is -1 (so are all the args), signalling an error.

**Comment by Xyene** [comment]
This is worked around, though a fix is unlikely.
