### ISSUE TITLE
Judge failing to connect to server (bad request syntax)

### ISSUE THREAD

**Issue by drmalex07** [DMOJ/judge#268]
Hello, I am trying to setup a simple pair of (site,judge) to evaluate DMOJ.

I followed the instructions to setup both components (i only changed database encoding to utf8, otherwise migrate command failed because of key overflows).
 
I am now trying to connect judge to sever:
```
dmoj -c config.yml -p 8000 127.0.0.1
``` 

This fails, and at server-side the following message is logged:
```
[25/Aug/2017 09:42:28] code 400, message Bad request syntax ("\x00\x00\x00\xe5x\x9ce\xd0\xb1n\xc20\x10\x06\xe0W\xb1\xbc\xe2Vv\x9c4\x85-\xa5t\x80\x0eQ+\xb5C\x94\xc1\xd8WRb0r\xa0\xb4B\xbc{\xcf8\xca\x00\x9bu\xdf\xef\xff\xa4;\xd1oC'\x84Z\xa7\x95\xbd[\x1f\xcc")
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/home/malex/temp/dmoj-site/pyenv/local/lib/python2.7/site-packages/django/utils/log.py", line 192, in format
    return super(ServerFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 11: ordinal not in range(128)
```

**Comment by Xyene** [comment]
Very late reply, but the issue is connecting the judge to the HTTP port (8000); this can never work. A judge must connect to a bridge instance (`manage.py runbridged`). There's a number of other tickets floating around regarding this, like #226.

Eventually the documentation should be updated to mention in bold text that the bridge *must* be set up to connect a judge, and is *not* an optional component.
