### ISSUE TITLE
I have already setup in windows finally, but still some Error here when I run dmoj

### ISSUE THREAD

**Issue by sirono0466** [DMOJ/judge#273]
First of all, what have I do :

1. reinstall VC2015 build tool
2. move all file in "Windows Kits\10\Lib\10.0.10240.0" to "Windows Kits\10\Lib\wdf"
3. move all file in  "Windows Kits\10\Include\10.0.10240.0" to "Windows Kits\10\Include\wdf"
**(I don't know why cython always find header file in "wdf", but all file is actually in "10.0.10240.0" and this file is actually with the VC++14.0 build tools. if I don't do that, it will miss many file like "io.h" "basetsd.h" and other standard C header)**
4. build dmoj with python 3 and
**it is still some bug said xxx.lib can not found xxx can not open at the first time, but success at the second time**
5. use 2to3 to change all print xx to print(xx), because python 3 does not suppose to do that.
**(Syntax Error)**

And, Finally I can setup the dmoj but when I try to run it.....
Here is the Error Message

**Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\dmoj-script.py", line 11, in <module>
    load_entry_point('dmoj', 'console_scripts', 'dmoj')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 565, in load_entry_point
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2598, in load_entry_point
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2258, in load
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "d:\xxx\judge\dmoj\judge.py", line 13, in <module>
    from dmoj import packet, graders
  File "d:\xxx\judge\dmoj\packet.py", line 12, in <module>
    from dmoj import sysinfo
  File "d:\xxx\judge\dmoj\sysinfo.py", line 38, in <module>
    _load_thread = SystemLoadThread()
  File "d:\xxx\judge\dmoj\sysinfo.py", line 26, in __init__
    self.counter = PerformanceCounter(r'\System\Processor Queue Length', r'\Processor(_Total)\% Processor Time')
  File "d:\xxx\judge\dmoj\utils\winperfmon.py", line 62, in __init__
    PdhAddCounter(self._query, path, 0, byref(handle))
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
Exception ignored in: <bound method PerformanceCounter.close of <dmoj.utils.winperfmon.PerformanceCounter object at 0x000002857326D940>>
Traceback (most recent call last):
  File "d:\xxx\judge\dmoj\utils\winperfmon.py", line 67, in close
    PdhCloseQuery(self._query)
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
\pkg_resources\__init__.py", line 2598, in load_entry_point
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2258, in load
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "d:\xxx\judge\dmoj\judge.py", line 13, in <module>
    from dmoj import packet, graders
  File "d:\xxx\judge\dmoj\packet.py", line 12, in <module>
    from dmoj import sysinfo
  File "d:\xxx\judge\dmoj\sysinfo.py", line 38, in <module>
    _load_thread = SystemLoadThread()
  File "d:\xxx\judge\dmoj\sysinfo.py", line 26, in __init__
    self.counter = PerformanceCounter(r'\System\Processor Queue Length', r'\Processor(_Total)\% Processor Time')
  File "d:\xxx\judge\dmoj\utils\winperfmon.py", line 62, in __init__
    PdhAddCounter(self._query, path, 0, byref(handle))
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
Exception ignored in: <bound method PerformanceCounter.close of <dmoj.utils.winperfmon.PerformanceCounter object at 0x000002857326D940>>
Traceback (most recent call last):
  File "d:\xxx\judge\dmoj\utils\winperfmon.py", line 67, in close
    PdhCloseQuery(self._query)
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert**

**Comment by quantum5** [comment]
Python 3 is not supported at this time.

**Comment by sirono0466** [comment]
And I also tried to build up with python 2
then cython will try to find out the header file in "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC" and show up there is missing "basetsd.h"
I have try install some build tools like VC++ for python, VS 2008 build tools
but still not work
