### ISSUE TITLE
go executor is not PY3 compliant

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/judge#443]
```
Traceback (most recent call last):
 File "/code/judge/dmoj/judge.py", line 279, in get_grader_from_source
   grader = grader_class(self, problem, language, utf8bytes(source))
 File "/code/judge/dmoj/graders/base.py", line 10, in __init__
   self.binary = self._generate_binary()
 File "/code/judge/dmoj/graders/standard.py", line 176, in _generate_binary
   unbuffered=self.problem.config.unbuffered)
 File "/code/judge/dmoj/executors/base_executor.py", line 321, in __call__
   obj.create_files(*args, **kwargs)
 File "/code/judge/dmoj/executors/GO.py", line 43, in create_files
   source_code = decomment(source_code).strip()
 File "/code/judge/dmoj/executors/GO.py", line 8, in <lambda>
   decomment = lambda x: recomment.sub('', x)
TypeError: sequence item 1: expected a bytes-like object, str found
```

**Comment by kiritofeng** [comment]
This has been deployed in prod.
