### ISSUE TITLE
Input/Output files with numerical file names causes exception

### ISSUE THREAD

**Issue by plasmatic1** [DMOJ/judge#454]
If you attempt to submit to a problem with numerical file names for input/output, the judge crashes with the following exception:

*Note: this was done using the dmoj cli*

```
Traceback (most recent call last):
  File "/mnt/e/dmoj/judge/dmoj/judge.py", line 188, in _begin_grading
    for result in self.grade_cases(grader, problem.cases, short_circuit=short_circuit):
  File "/mnt/e/dmoj/judge/dmoj/judge.py", line 243, in grade_cases
    is_short_circuiting=is_short_circuiting):
  File "/mnt/e/dmoj/judge/dmoj/judge.py", line 267, in grade_cases
    result = grader.grade(case)
  File "/mnt/e/dmoj/judge/dmoj/graders/standard.py", line 33, in grade
    input = case.input_data()  # cache generator data
  File "/mnt/e/dmoj/judge/dmoj/problem.py", line 239, in input_data
    return self._normalize(self.problem.problem_data[self.config['in']]) if self.config['in'] else ''
  File "/mnt/e/dmoj/judge/dmoj/problem.py", line 93, in __missing__
    return open(os.path.join(base, key), 'rb').read()
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'int' object has no attribute 'startswith'
```

## How to produce

Create a problem with an `init.yml` similar to this one:

```yaml
archive: data.zip
test_cases:
- points: 0
  batched:
  - {in: sample.in, out: sample.out}
- points: 100
  batched:
  - {in: 1, out: 1out}
  - {in: 2, out: 2out}
  - {in: 3, out: 3out}
  - {in: 4, out: 4out}
  - {in: 5, out: 5out}
  - {in: 6, out: 6out}
  - {in: 7, out: 7out}
  - {in: 8, out: 8out}
  - {in: 9, out: 9out}
  - {in: 10, out: 10out}
  - {in: 11, out: 11out}
  - {in: 12, out: 12out}
  - {in: 13, out: 13out}
  - {in: 14, out: 14out}
  - {in: 15, out: 15out}
  - {in: 16, out: 16out}
  - {in: 17, out: 17out}
  - {in: 18, out: 18out}
  - {in: 19, out: 19out}
  - {in: 20, out: 20out}
```

Add the corresponding input and output files to the `data.zip` archive.

Then, submit to the problem in some way.

**Comment by kiritofeng** [comment]
Solution: use quotes.

**Comment by plasmatic1** [comment]
thanks!
