### ISSUE TITLE
java_executor throws an exception when judging an interactive problem where the program crashes

### ISSUE THREAD

**Issue by xiaowuc1** [DMOJ/judge#485]
Production reproduction: https://dmoj.ca/submission/1595554

```
Traceback (most recent call last):
 File "/code/judge/dmoj/graders/custom.py", line 15, in grade
   return self._grader.grade(case)
 File "/code/judge/dmoj/graders/standard.py", line 66, in grade
   self.update_feedback(check, error, process, result)
 File "/code/judge/dmoj/graders/standard.py", line 83, in update_feedback
   getattr(self.binary, 'get_feedback', lambda x, y, z: '')(error, result, process)))
 File "/code/judge/dmoj/executors/java_executor.py", line 121, in get_feedback
   if b'Error: Main method not found in class' in stderr:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ehhthing** [comment]
Also reproducible with C#: 
https://dmoj.ca/submission/1595615

```
Traceback (most recent call last):
 File "/code/judge/dmoj/graders/custom.py", line 15, in grade
   return self._grader.grade(case)
 File "/code/judge/dmoj/graders/standard.py", line 66, in grade
   self.update_feedback(check, error, process, result)
 File "/code/judge/dmoj/graders/standard.py", line 83, in update_feedback
   getattr(self.binary, 'get_feedback', lambda x, y, z: '')(error, result, process)))
 File "/code/judge/dmoj/executors/mono_executor.py", line 71, in get_feedback
   if b'Garbage collector could not allocate' in stderr:
TypeError: argument of type 'NoneType' is not iterable
```
