### ISSUE TITLE
Abysmal error handling

### ISSUE THREAD

**Issue by Xyene** [DMOJ/judge#8]
The judge servers were written to "chug along", but this has a terrible effect on error messages.

The following traceback is generated when a user misconfigures a problem:

```
Traceback (most recent call last):

  File "/code/site/judge/bridge/judgehandler.py", line 199, in on_bad_problem
    raise ValueError('\n\n' + packet['message'])

ValueError:

Traceback (most recent call last):
  File "/judge/judge/judge.py", line 185, in _begin_grading
    with open(os.path.join(get_problem_root(problem_id), 'init.json'), 'r') as init_file:
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Intuitive, right? Very helpful to those who are not familiar with the judge's source code.

**Comment by Xyene** [comment]
This has been much improved over time and in `judge2`, to the extent where it is no longer a problem.
